# Generated by Django 2.0.4 on 2018-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180426_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='pic',
            field=models.ImageField(upload_to='static/media/goods'),
        ),
    ]
