# Generated by Django 2.0.4 on 2018-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='is_pay',
            field=models.IntegerField(default=0),
        ),
    ]
